### PR TITLE
Adds aws bot accounts

### PR DESCRIPTION
**Pull request by udondan**
All 4 accounts periodically scrape thw AWS documentation and toot changes.

- iamfloyd: IAM actions, resources and condition keys (maintained by me)
- cfnupdates: CloudFormation release notes
- mamip_aws: AWS Managed IAM Policies Changes
- awswhatsnew: News from https://aws.amazon.com/new

### CODE REVIEW

**Comment by joschi** [comment]
There's also https://botsin.space/@awswhatsnew in case you're interested in adding it. 😅

**Comment by udondan** [comment]
Thanks @joschi, added. Not sure though if @gunnargrosch want's to have this file added? :)

**Comment by gunnargrosch** [comment]
@udondan I like it! But maybe we can change it to aws-bots.csv to make it clearer that the accounts are bots and also to widen the scope from only news?

**Comment by udondan** [comment]
Makes perfect sense. I updated the filename.

**Comment by gunnargrosch** [comment]
Lgtm!

**Comment by udondan** [comment]
Now we should add @awsbubble@awscommunity.social to make the circle complete 😸

**Comment by gunnargrosch** [comment]
Yes! That's going to be an inception moment when the bot announces itself. I'll add it. 😅

**Pull request merged**
